name: GitHub Pages
on:
  workflow_dispatch:
  # 1) Commit and push
  # 2) Go to Setting => Pages => Build and deployment: select "Deploy from a branch", "gh-pages", "/ (root)" => click "Save"
  # 3) Go to Setting => Environments => Deployment branches: select "All branches"
  push:
    tags: [ '*' ]
    branches: [ '*' ]
    pull_request: [ '*' ]
env:
  NODE_VERSION: 18.4.0
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        id: ci
        with:
          path: |
            ~/.npm
            ~/.node
          key: ${{ runner.os }}-${{ hashFiles('**/package.json', '**/package-lock.json') }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm i -ED @parcel/css-linux-x64-gnu
      - run: npm install -E --omit=optional
      - run: npm run github-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
